### PR TITLE
add recommended package to support previous api

### LINKED ISSUE #9: eslint-config-recommended v3 documentation incorrect
When upgrading from v2 to v3, the instructions in the README are no longer valid. Running `npm install eslint-config-recommended` now installs the `packages/` directory so using `recommended/node` no longer works.

image

image

### PR DESCRIPTION
**Pull request by shannonmoeller**
Closes #9

### CODE REVIEW

**Comment by kunalgolani** [comment]
Awesome. Couple of questions:
1. Should I republish this as `v3.0.0`, or update to `v3.1.0`, or bump it up another major version?
2. I'm not actively using this package anymore, which is why it's kinda not well maintained. Would you like to be a collaborator on this and be able to publish updates on your own somehow? Issues are super-rare.

**Comment by shannonmoeller** [comment]
1. I recommend v3.1.0. Technically we only fixed a bug here, but the change feels heavier than a v3.0.1.
2a. Sorry to hear that this isn't well maintained. It's a handy set of rules. What are you using instead, if anything?
2b. I'd be happy to be a collaborator.

**Comment by kunalgolani** [comment]
Hey @shannonmoeller 

Sorry for being late.

1. I'll leave it to you. I guess I'll have to figure out how to share npm publish permissions.
2. Got no private projects right now, and work has their own config.
3. Yay, adding you to this repo right now, still have to figure out npm collaboration.

**Comment by kunalgolani** [comment]
@shannonmoeller I need your npm username for sharing publish permissions.

**Comment by shannonmoeller** [comment]
I’m http://npm.im/~shannonmoeller

**Pull request merged**
